#include<vector>
#include<sys/types.h>
#include<sys/wait.h>
#include<sstream>
#include<iostream>
#include<unistd.h>
#include<string>
#include<fstream>
#include<fcntl.h>
#include<string.h>
#include<algorithm>
#include<termios.h>
#include<list>
#include<signal.h>
#include<errno.h>
#include<map>